# Problem 1 

In [11]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array_1 = np.random.randint(0,100,size=5)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(array_1))


[48 53 70 80 91]


# Problem 2

In [28]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
print(np.array([10, 15, 30, 45, 60]))

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
print(np.random.randint(5,15))
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
print(np.arange(50, 101, 5))

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
print(np.zeros(10))

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
print(np.ones(10))

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
print(np.linspace(0, 100, 5))

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
print(np.random.randint(10,30,size=5))

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
print(np.random.uniform(-1, 1, 10))

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
random_matrix = np.random.randint(10, 51, size=(3, 5))

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
toplam_satir = np.sum(random_matrix, axis=1)
print(toplam_satir)

toplam_sutun = np.sum(random_matrix, axis=0)
print(toplam_sutun)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
max_value = np.max(random_matrix)
min_value = np.min(random_matrix)
mean_value = np.mean(random_matrix)

print(max_value)
print(min_value)
print(mean_value)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.max(random_matrix)
print(max_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
ornek = np.arange(10, 21)
print(ornek[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(ornek[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(random_matrix[0, :])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(random_matrix[1, 2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(random_matrix[:, 0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(np.square(random_matrix))

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
range_3_5 = np.random.randint(-50, 51, size=(3, 5))
postive_numbers = range_3_5[(range_3_5 > 0) & (range_3_5 % 2 == 0)]

[10 15 30 45 60]
11
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[23 11 10 20 22]
[ 0.22251872 -0.05643742 -0.53900885 -0.99487538  0.10869942 -0.44904478
 -0.95424519 -0.60133731 -0.82058697  0.34752444]
[175 157 155]
[ 74  96 123 116  78]
50
15
32.46666666666667
50
[10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
[28 45 38 25 39]
35
[28 21 25]
[[ 784 2025 1444  625 1521]
 [ 441 1089 1225 1936  576]
 [ 625  324 2500 2209  225]]
