# Problem 1

In [9]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0,11,size=5)
print(matris)

# 3 - matris'in boyutunu öğrenin
print(matris.shape)

# 4 - matris'i yeniden boyutlandırın
print(matris.reshape((5,1)))

# 5 - matris'in boyut sayısını öğrenin
print(matris.ndim)


[ 2  6  2 10  5]
(5,)
[[ 2]
 [ 6]
 [ 2]
 [10]
 [ 5]]
1


# Problem 2

In [24]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris_2 = np.arange(1,10,2)
print(matris_2)

# 2 - Oluşturduğunuz matrisi parçalayın
parcali = np.array_split(matris_2, 2)
print(parcali)

# 3 - Parçalanmış matrisleri birleştirin
birlesik = np.concatenate(parcali)
print(birlesik)


[1 3 5 7 9]
[array([1, 3, 5]), array([7, 9])]
[1 3 5 7 9]


# Problem 3

In [27]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matrix = np.random.choice(np.arange(5, 101, 2), 10, replace=False)
print(matrix)

# 2 - matris'in özelliklerini inceleyin
print("Boyut (shape):", matrix.shape)
print("Boyut sayısı (ndim):", matrix.ndim)
print("Eleman sayısı (size):", matrix.size)
print("Veri tipi (dtype):", matrix.dtype)


[17 63 87 97 19 83 37  7 77  5]
Boyut (shape): (10,)
Boyut sayısı (ndim): 1
Eleman sayısı (size): 10
Veri tipi (dtype): int64
